// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLMP.DAL.Models;

#nullable disable

namespace QLMP.DAL.Migrations
{
    [DbContext(typeof(QuanLyMyPhamContext))]
    partial class QuanLyMyPhamContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QLMP.DAL.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("QLMP.DAL.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItem", (string)null);
                });

            modelBuilder.Entity("QLMP.DAL.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaSp")
                        .HasColumnType("int");

                    b.Property<double?>("DonGia")
                        .HasColumnType("float");

                    b.Property<double?>("GiamGia")
                        .HasColumnType("float");

                    b.Property<short?>("SoLuong")
                        .HasColumnType("smallint");

                    b.HasKey("MaHoaDon", "MaSp");

                    b.HasIndex("MaSp");

                    b.ToTable("ChiTietHoaDon", (string)null);
                });

            modelBuilder.Entity("QLMP.DAL.Models.ConTact", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("ConTent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("ConTact", (string)null);
                });

            modelBuilder.Entity("QLMP.DAL.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"), 1L, 1);

                    b.Property<int?>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<DateTime?>("NgayLapHd")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayLapHD");

                    b.Property<decimal?>("TongSl")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("TongSL");

                    b.HasKey("MaHoaDon")
                        .HasName("PK__HoaDon__835ED13B10DD4A71");

                    b.HasIndex("MaKh");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("QLMP.DAL.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKh"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Sdt")
                        .HasColumnType("int")
                        .HasColumnName("SDT");

                    b.Property<string>("TenKh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenKH");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MaKh")
                        .HasName("PK__KhachhHa__2725CF1EEB1BC594");

                    b.HasIndex("UserId");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("QLMP.DAL.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("MaLoaiSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaLoaiSP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiSp"), 1L, 1);

                    b.Property<string>("TenLoaiSp")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TenLoaiSP");

                    b.HasKey("MaLoaiSp")
                        .HasName("PK__LoaiSanP__1224CA7C35FBE213");

                    b.ToTable("LoaiSanPham", (string)null);
                });

            modelBuilder.Entity("QLMP.DAL.Models.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RoleID");

                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("QLMP.DAL.Models.SanPham", b =>
                {
                    b.Property<int>("MaSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSp"), 1L, 1);

                    b.Property<double?>("Gia")
                        .HasColumnType("float");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaLoaiSp")
                        .HasColumnType("int")
                        .HasColumnName("MaLoaiSP");

                    b.Property<string>("TenSp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenSP");

                    b.HasKey("MaSp")
                        .HasName("PK__SanPham__2725081CA07072F7");

                    b.HasIndex("MaLoaiSp");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("QLMP.DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PassWord")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Role");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("QLMP.DAL.Models.Cart", b =>
                {
                    b.HasOne("QLMP.DAL.Models.KhachHang", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Cart_KhachHang");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QLMP.DAL.Models.CartItem", b =>
                {
                    b.HasOne("QLMP.DAL.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .IsRequired()
                        .HasConstraintName("FK_CartItem_Cart");

                    b.HasOne("QLMP.DAL.Models.SanPham", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_CartItem_SanPham");

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("QLMP.DAL.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("QLMP.DAL.Models.HoaDon", "MaHoaDonNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHoaDon")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietHoaDon_HoaDon");

                    b.HasOne("QLMP.DAL.Models.SanPham", "MaSpNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietHoaDon_SanPham");

                    b.Navigation("MaHoaDonNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("QLMP.DAL.Models.HoaDon", b =>
                {
                    b.HasOne("QLMP.DAL.Models.KhachHang", "MaKhNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK_HoaDon_KhachHang");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("QLMP.DAL.Models.KhachHang", b =>
                {
                    b.HasOne("QLMP.DAL.Models.User", "User")
                        .WithMany("KhachHangs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_KhachHang_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QLMP.DAL.Models.SanPham", b =>
                {
                    b.HasOne("QLMP.DAL.Models.LoaiSanPham", "MaLoaiSpNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaLoaiSp")
                        .HasConstraintName("FK_SanPham_LoaiSanPham");

                    b.Navigation("MaLoaiSpNavigation");
                });

            modelBuilder.Entity("QLMP.DAL.Models.User", b =>
                {
                    b.HasOne("QLMP.DAL.Models.Role", "RoleNavigation")
                        .WithMany("Users")
                        .HasForeignKey("Role")
                        .IsRequired()
                        .HasConstraintName("FK_User_Role");

                    b.Navigation("RoleNavigation");
                });

            modelBuilder.Entity("QLMP.DAL.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("QLMP.DAL.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("QLMP.DAL.Models.KhachHang", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("QLMP.DAL.Models.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("QLMP.DAL.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("QLMP.DAL.Models.SanPham", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("QLMP.DAL.Models.User", b =>
                {
                    b.Navigation("KhachHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
